name: Build uvg266 x86_64/amd64 Intel CPU Progress Process Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Git clone uvg266
      run: git clone --depth=1 https://github.com/ultravideo/uvg266
    - name: Build uvg266
      run: cd uvg266 && cd build && cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF -DCMAKE_OSX_ARCHITECTURES=x86_64 .. -G "Xcode" && cmake --build . --config Release && cd ../../
    - name: Zip Release of uvg266
      uses: TheDoctor0/zip-release@0.7.1
      with:
        filename: uvg266
        path: /Users/runner/work/uvg266macbuild/uvg266macbuild/uvg266/build
    - name: Upload a Build Artifact of uvg266
      uses: actions/upload-artifact@v4.0.0
      with:
        name: uvg266
        path: ./uvg266.zip
