name: Build uvg266 arm64 (aarch64 / armv8) Mac M1 / M2 / M3+
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Git clone uvg266
      run: git clone --depth=1 https://github.com/ultravideo/uvg266
    - name: Build vvenc
      run: cd vvenc && mkdir build && cd build && cmake -DCMAKE_OSX_ARCHITECTURES=arm64 -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF .. -G "Xcode" && cmake --build . --config Release && cd ../../
    - name: Zip Release of vvenc
      uses: TheDoctor0/zip-release@0.7.1
      with:
        filename: uvg266_arm64.zip
        path: ./uvg266/build/uvg266
